# Generated by Django 4.1.5 on 2023-01-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='actice',
            new_name='active',
        ),
    ]
